import { Inter } from "next/font/google";

import { css } from "@/styled-system/css";
import { SITE_TITLE } from "@three/const";

import type { Metadata } from "next";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: SITE_TITLE,
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const color = css({ color: "ultra.800" });
  return (
    <html lang="ja">
      <body className={inter.className}>
        <div className={color}>{children}</div>
      </body>
    </html>
  );
}
